export const WEATHER_CONDITIONS = {
    'thunderstorm with light rain': 'thunderstorms-rain',
    'thunderstorm with rain': 'thunderstorms-overcast-rain',
    'thunderstorm with heavy rain': 'thunderstorms-extreme-rain',
    'light thunderstorm': 'thunderstorms',
    'thunderstorm':'thunderstorms-overcast',
    'heavy thunderstorm':'thunderstorms-extreme',
    'ragged thunderstorm':'extreme-thunderstorms-extreme',
    'thunderstorm with light drizzle':'thunderstorms-drizzle',
    'thunderstorm with drizzle':'thunderstorms-overcast-drizzle',
    'thunderstorm with heavy drizzle':'thunderstorms-extreme-drizzle',
    'light intensity drizzle':'drizzle',
    'drizzle':'overcast-day-drizzle',
    'heavy intensity drizzle':'extreme-drizzle',
    'light intensity drizzle rain':'drizzle',
    'drizzle rain':'overcast-day-drizzle',
    'heavy intensity drizzle rain':'extreme-drizzle',
    'shower rain and drizzle':'drizzle',
    'heavy shower rain and drizzle':'extreme-drizzle',
    'shower drizzle':'drizzle',
    'light rain':'rain',
    'moderate rain':'rain',
    'heavy intensity rain':'overcast-rain',
    'very heavy rain':'extreme-rain',
    'extreme rain':'extreme-rain',
    'freezing rain':'sleet',
    'light intensity shower rain':'rain',
    'shower rain':'rain',
    'heavy intensity shower rain':'extreme-rain',
    'ragged shower rain':'rain',
    'light snow':'snow',
    'snow':'overcast-snow',
    'heavy snow':'extreme-snow',
    'sleet':'overcast-sleet',
    'light shower sleet':'sleet',
    'shower sleet':'sleet',
    'light rain and snow':'sleet',
    'rain and snow':'overcast-sleet',
    'light shower snow':'snow',
    'shower snow':'overcast-snow',
    'heavy shower snow':'extreme-snow',
    'mist':'mist',
    'smoke':'smoke',
    'haze':'haze',
    'sand/dust whirls':'dust',
    'fog':'fog',
    'sand':'dust',
    'dust':'dust',
    'volcanic ash':'volcano',
    'squalls':'waterspout',
    'tornado':'tornado',
    'clear sky':'clear-day',
    'few clouds':'mostly-clear-day',
    'scattered clouds':'cloudy',
    'broken clouds':'overcast',
    'overcast clouds':'extreme',
}